import ConfirmDialog from "@/components/common/ConfirmModal";
import { AppSidebar } from "@/components/sideBar/AppSidebar";
import { SiteHeader } from "@/components/sideBar/SiteHeader";
import { SidebarProvider, SidebarInset } from "@/components/ui/sidebar";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function PublicLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SidebarProvider className="h-screen">
      <AppSidebar />
      <SidebarInset className="flex flex-col h-full ">
        <div className="sticky top-0 z-50 bg-white border-b">
          <SiteHeader />
        </div>
        <div className="@container/main overflow-y-auto">
          <div className="flex flex-col gap-2 p-2 md:gap-2 md:py-2 ">
            {children}
            <ConfirmDialog />
          </div>
        </div>
      </SidebarInset>
    </SidebarProvider>
  );
}
